### PR TITLE
Adding typewriter effect

### PR DESCRIPTION
**Pull request by helper-uttam**
This will show your name with an animation of typewriter

### CODE REVIEW

**Comment by Sin-Sumit** [comment]
I liked it and Thank you for the typewriter effect.

**Comment by helper-uttam** [comment]
> I liked it and Thank you for the typewriter effect.

Then why dis you close this PR linstead of merging ?

**Comment by Sin-Sumit** [comment]
Because I have another pull request which has much more changes.

**Comment by Sin-Sumit** [comment]
Because I have another pull request which has much more changes.

**Comment by Sin-Sumit** [comment]
But I have a suggestion if you can check the readme now, you will get what I am saying, and the suggestion is can you change the typewriter effect like whenever the readme page opens, then the typewriter starts and stops after completing the sentence.
Like no repetition in it.

**Comment by helper-uttam** [comment]
> But I have a suggestion if you can check the readme now, you will get what I am saying, and the suggestion is can you change the typewriter effect like whenever the readme page opens, then the typewriter starts and stops after completing the sentence.
> Like no repetition in it.

hey I saw your readme It's working perfectly it starts when someone visit your profile and keep repeating? It never stops!

**Comment by helper-uttam** [comment]
> Because I have another pull request which has much more changes.

then you can merge both changes :)

**Comment by Sin-Sumit** [comment]
> > But I have a suggestion if you can check the readme now, you will get what I am saying, and the suggestion is can you change the typewriter effect like whenever the readme page opens, then the typewriter starts and stops after completing the sentence.
> > Like no repetition in it.
> 
> hey I saw your readme It's working perfectly it starts when someone visit your profile and keep repeating? It never stops!

Can you do it? So, it stops after one time.

**Comment by helper-uttam** [comment]
> > > But I have a suggestion if you can check the readme now, you will get what I am saying, and the suggestion is can you change the typewriter effect like whenever the readme page opens, then the typewriter starts and stops after completing the sentence.
> > > Like no repetition in it.
> > 
> > 
> > hey I saw your readme It's working perfectly it starts when someone visit your profile and keep repeating? It never stops!
> 
> Can you do it? So, it stops after one time.

No it don't stop. I had checked that again

**Comment by Sin-Sumit** [comment]
Ok, Thank you!

**Pull request closed without merging**
